force-app/main/default/objects/CAPA__c/CAPA__c.object-meta.xml
<CustomObject>
    <label>CAPA</label>
    <nameField>
        <displayFormat>CAPA-{00000}</displayFormat>
        <label>CAPA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CAPAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CAPA__c/fields/DeviationId__c.field-meta.xml
<CustomField>
    <fullName>DeviationId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deviation</label>
    <referenceTo>Deviation__c</referenceTo>
    <relationshipLabel>CAPAs</relationshipLabel>
    <relationshipName>CAPAs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CAPA__c/fields/Severity__c.field-meta.xml
<CustomField>
    <fullName>Severity__c</fullName>
    <label>Severity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Critical</fullName>
            </value>
            <value>
                <fullName>Major</fullName>
            </value>
            <value>
                <fullName>Minor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CAPA__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Inprogress</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deviation__c/Deviation__c.object-meta.xml
<CustomObject>
    <label>Deviation</label>
    <nameField>
        <displayFormat>DEV-{00000}</displayFormat>
        <label>Deviation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deviations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deviation__c/fields/CAPA_Required__c.field-meta.xml
<CustomField>
    <fullName>CAPA_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CAPA Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Deviation__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Process</fullName>
            </value>
            <value>
                <fullName>Equipment</fullName>
            </value>
            <value>
                <fullName>Material</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deviation__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <label>Due_Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Deviation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Inprogress</fullName>
            </value>
            <value>
                <fullName>Close</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DeviationRestService.cls
@RestResource(urlMapping='/qms/deviations/*')
global with sharing class DeviationRestService {
    @HttpGet
    global static List<SObject> getDeviations() {
        RestRequest req = RestContext.request;
        String uri = req.requestURI;
        List<String> parts = uri.split('/');
        List<SObject> result = new List<SObject>();
        
		if (parts.size() == 3) {        // URL - services/apexrest/qms/deviations
            result = getAllDeviations();
            return result;
        }
        else if (parts.size() == 4) {   // URL - services/apexrest/qms/deviations/a01xxxx
            result = getDeviationById(parts[3]);
            return result;
        }
        else if (parts.size() == 5 && parts[4] == 'capas') { // URL - services/apexrest/qms/deviations/a01xxxx/capas
            result = getCAPAsByDeviationId(parts[3]);
            return result;
        }
        return result;   
    }
    @HttpPost
    global static String createDeviation() {
        RestRequest req = RestContext.request;
        String body = req.requestBody.toString();

        Deviation__c dev = (Deviation__c) JSON.deserialize(body, Deviation__c.class);
        insert dev;

        return 'Created Deviation with Id: ' + dev.Id;
    }
    private static List<SObject> getAllDeviations() {
        return [SELECT Id, Name, Status__c, Category__c, Severity__c, Due_Date__c, CAPA_Required__c FROM Deviation__c LIMIT 50];
    }
    private static List<SObject> getDeviationById(String id) {
        return [SELECT Id, Name, Status__c, Category__c, Severity__c, Due_Date__c, CAPA_Required__c FROM Deviation__c WHERE Id = :id];
    }
    private static List<SObject> getCAPAsByDeviationId(String id) {
        return [SELECT Id, Name, Status__c, Severity__c, Due_Date__c FROM CAPA__c WHERE DeviationId__c = :id];
    }
}