force-app/main/default/objects/CAPA__c/CAPA__c.object-meta.xml
<CustomObject>
    <label>CAPA</label>
    <nameField>
        <displayFormat>CAPA-{00000}</displayFormat>
        <label>CAPA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CAPAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CAPA__c/fields/DeviationId__c.field-meta.xml
<CustomField>
    <fullName>DeviationId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deviation</label>
    <referenceTo>Deviation__c</referenceTo>
    <relationshipLabel>CAPAs</relationshipLabel>
    <relationshipName>CAPAs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CAPA__c/fields/Severity__c.field-meta.xml
<CustomField>
    <fullName>Severity__c</fullName>
    <label>Severity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Critical</fullName>
            </value>
            <value>
                <fullName>Major</fullName>
            </value>
            <value>
                <fullName>Minor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CAPA__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Inprogress</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deviation__c/Deviation__c.object-meta.xml
<CustomObject>
    <label>Deviation</label>
    <nameField>
        <displayFormat>DEV-{00000}</displayFormat>
        <label>Deviation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deviations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deviation__c/fields/CAPA_Required__c.field-meta.xml
<CustomField>
    <fullName>CAPA_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CAPA Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Deviation__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <label>Due_Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Deviation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Inprogress</fullName>
            </value>
            <value>
                <fullName>Close</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DeviationTriggerHandler.cls
public with sharing class DeviationTriggerHandler {
    public static void run() {
        if(Trigger.isAfter && Trigger.isInsert) {
            afterInsert(Trigger.new);
        }
    }
    
    public static void afterInsert(List<Deviation__c> deviations) {
        List<CAPA__c> capaList = new List<CAPA__c>();
        for (Deviation__c dev: deviations) {
            if (dev.CAPA_Required__c) {
                CAPA__c newCapa = new CAPA__c(
                    DeviationId__c = dev.Id,
                    Due_Date__c = dev.Due_Date__c,
                    Severity__c = dev.Severity__c,
                    Status__c = 'Open'
                );
                capaList.add(newCapa);
            }
        }
        if (!capaList.isEmpty()) {
            insert capaList;
        }
    }
}